### ISSUE TITLE
make skillsbot live for bocoup internal use

### ISSUE THREAD

**Issue by cowboy** [bocoup/skillsbot#50]
- [x] create `skillsbot` db
- [x] create actual `skillsbot` slack app
- [x] add slack app credentials to `skillsbot-slack` secret
- [x] add db credentials to `skillsbot-db` secret
- [x] add npm shrinkwrap file
- [x] deploy `skillsbot` to production server
- [x] add `skillsbot` to Bocoup Slack
- [x] allow production server to import Bocoup expertise data #51 
- [x] prepare `expertise` command removal from Robocoup https://github.com/bocoup/bots/issues/159
- [x] implement command naming changes per #11 
- [x] import Bocoup expertise data with `bocoup-import` command, verify that it imported correctly
- [x] actually remove `expertise` command from Robocoup https://github.com/bocoup/bots/issues/158

**Comment by cowboy** [comment]
Done!

**Comment by tkellen** [comment]
Nice work @cowboy @jess @jennschiffer and everyone who did user testing!!!
